name: dbd_companion
description: Dead by Daylight Companion App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Utils
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/maps/
    - assets/maps/macmillan/
    - assets/maps/autohaven/
    - assets/maps/coldwind/
    - assets/maps/crotus_prenn/
    - assets/maps/haddonfield/
    - assets/maps/backwater_swamp/
    - assets/maps/lery/
    - assets/maps/springwood/
    - assets/maps/red_forest/
    - assets/maps/gideon/
    - assets/maps/hawkins/
    - assets/maps/yamaoka/
    - assets/maps/ormond/
    - assets/maps/raccoon_city/
    - assets/maps/eyrie_of_crows/
    - assets/maps/dvarka/
    - assets/maps/withered_isle/
    - assets/maps/toba_landing/
    - assets/maps/greenville/
    - assets/maps/forsaken_boneyard/
