name: dbd_companion
description: Dead by Daylight Companion App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Utils
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/images/perks/
    - assets/data/maps/MacMillan Estate/
    - assets/data/maps/Autohaven Wreckers/
    - assets/data/maps/Coldwind Farm/
    - assets/data/maps/Crotus Prenn Asylum/
    - assets/data/maps/Haddonfield/
    - assets/data/maps/Backwater Swamp/
    - "assets/data/maps/Léry's Memorial Institute/"
    - assets/data/maps/Badham/
    - assets/data/maps/Red Forest/
    - assets/data/maps/Gideon Meat Plant/
    - assets/data/maps/Hawkins National Laboratory/
    - assets/data/maps/Yamaoka Estate/
    - assets/data/maps/Ormond/
    - assets/data/maps/Raccoon City/
    - assets/data/maps/Decimated Borgo/
    - assets/data/maps/Dvarka Deepwood/
    - assets/data/maps/Forsaken Boneyard/
    - assets/data/maps/Grave of Glennvale/
    - assets/data/maps/Silent Hill/
    - assets/data/maps/Withered Isle/
