// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Ss4ErYp6pUWaQ2NejGo2Y-Nu3WEVWAg',
    appId: '1:465574423019:web:7a4d809d772457c26f51ae',
    messagingSenderId: '465574423019',
    projectId: 'dbd-companion',
    authDomain: 'dbd-companion.firebaseapp.com',
    storageBucket: 'dbd-companion.firebasestorage.app',
    measurementId: 'G-E97YSD7N2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSwuibg1G_gxJY1m12dZrUAPTFRsv8qA',
    appId: '1:465574423019:android:aa77f622843119346f51ae',
    messagingSenderId: '465574423019',
    projectId: 'dbd-companion',
    storageBucket: 'dbd-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1eNJNogmnhdt1aVvxB7QMxiSrJBBt1JA',
    appId: '1:465574423019:ios:3bac7be5fb51ae266f51ae',
    messagingSenderId: '465574423019',
    projectId: 'dbd-companion',
    storageBucket: 'dbd-companion.firebasestorage.app',
    iosClientId: '465574423019-4esm0g69fdng16ki2n63ubo49ul5klmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbdCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Ss4ErYp6pUWaQ2NejGo2Y-Nu3WEVWAg',
    appId: '1:465574423019:web:475d4d817ce048886f51ae',
    messagingSenderId: '465574423019',
    projectId: 'dbd-companion',
    authDomain: 'dbd-companion.firebaseapp.com',
    storageBucket: 'dbd-companion.firebasestorage.app',
    measurementId: 'G-SD9C6BD5EE',
  );
}
